spring.application.name=ticket

# Banco de dados — "postgres" é o nome do serviço no docker-compose
spring.datasource.url=jdbc:postgresql://postgres:5432/ticketdb
spring.datasource.username=spring_app
spring.datasource.password=spting_password

# DDL
spring.jpa.hibernate.ddl-auto=update

# Logs SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
